export const ethicEnum = [
  "Tagalog",
  "Cebuano",
  "Ilocano",
  "Bisaya",
  "Hiligaynon (Ilonggo)",
  "Waray",
  "Bicolano",
  "Kapampangan",
  "Pangasinense",
  "Maranao",
  "Maguindanao",
  "Tausug",
  "Kalinga",
  "Ibanag",
  "Ivatan",
  "Mangyan",
  "Lumad",
] as const;

export const motherTongueEnum = [
  "Tagalog (Filipino)",
  "Cebuano",
  "Ilocano",
  "Hiligaynon (Ilonggo)",
  "Waray",
  "Bikol",
  "Kapampangan",
  "Pangasinan",
  "Maguindanao",
  "Tausug",
  "Maranao",
  "Chavacano",
  "Kinaray-a",
  "Aklanon",
  "Ivatan",
  "Yakan",
  "Surigaonon",
  "Ibanag",
  "Itawis",
  "Kankanaey",
] as const;

export const religionEnum = ["Roman Catholic", "Islam", "Born-Again Christian", "Iglesia ni Cristo", "Aglipayan", "Buddhism", "Hinduism", "Judaism"] as const;

export const guardianRelationshipEnum = [
  "Step-parent",
  "Foster parent",
  "Legal guardian",
  "Grandparent",
  "Aunt",
  "Uncle",
  "Sister",
  "Brother",
  "Cousin",
  "Other family member",
  "Close family friend",
  "Custodian",
  "Godparent",
  "Legal custodian",
] as const;
