export const fakeData = [
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
  {
    LRN: "123456789",
    Name: "Doe, John A.",
    Sex: "M",
    BirthDate: "05/15/1995",
    AgeAsOfJune: 27,
    MotherTongue: "English",
    IP: "none",
    Religion: "Christian",
    Address: "123 Main Street, Central, Metroville, State",
    FatherName: "Doe, Mark B.",
    MotherMaidenName: "Smith, Mary C.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-9876",
    Remarks: "none",
  },
  {
    LRN: "987654321",
    Name: "Smith, Jane E.",
    Sex: "F",
    BirthDate: "03/20/1990",
    AgeAsOfJune: 32,
    MotherTongue: "Spanish",
    IP: "Tagalog",
    Religion: "Catholic",
    Address: "456 Oak Avenue, Suburbia, Townsville, County",
    FatherName: "Smith, Robert F.",
    MotherMaidenName: "Johnson, Susan G.",
    GuardianName: "Doe, Alice H.",
    RelationshipWithGuardian: "Aunt",
    ContactNumber: "555-5432",
    Remarks: "none",
  },
  {
    LRN: "555555555",
    Name: "Brown, David M.",
    Sex: "M",
    BirthDate: "12/10/1988",
    AgeAsOfJune: 35,
    MotherTongue: "French",
    IP: "none",
    Religion: "Protestant",
    Address: "789 Pine Street, Downtown, Cityville, District",
    FatherName: "Brown, Richard L.",
    MotherMaidenName: "Miller, Laura J.",
    GuardianName: "none",
    RelationshipWithGuardian: "none",
    ContactNumber: "555-1234",
    Remarks: "none",
  },
];
